name = "Kosmos"
uuid = "59329d5d-8742-42cc-b60b-014e218386a9"
authors = ["Kyando2 <amehikoji@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
